"""
bot.py 的工具常量(纯数据, 零外部引用) —— 2026-10-05 从 bot.py 搬出, 减小主文件体积。

搬运前置校验(实测):
  · TOOLS / TOOL_LABELS / HEAVY_KW 各只有 1 次顶层赋值
  · 无 append/extend/insert/pop/remove/clear/update 等原地修改
  · 无下标赋值 / del / +=  
  · 无 globals()['TOOLS'] 之类动态访问
所以搬走后 bot.py 侧改成 from .tools_schema import 即可, 行为完全不变。
搬完已用 ast.literal_eval 逐值比对, 与原定义 100% 一致。
"""

TOOL_LABELS = {
    "search": '<tg-emoji emoji-id="4958587679361991667">🔍</tg-emoji> 联网搜索',
    "shot": '<tg-emoji emoji-id="4925242532528391544">📸</tg-emoji> 网页截图',
    "url": '<tg-emoji emoji-id="4926961786462143784">🌐</tg-emoji> 抓取网页',
    "sh": '<tg-emoji emoji-id="4924919267519890977">💻</tg-emoji> 执行命令',
    "read": '<tg-emoji emoji-id="5258328383183396223">📖</tg-emoji> 读取文件',
    "write": '<tg-emoji emoji-id="5257965174979042426">📝</tg-emoji> 写入文件',
    "edit": '<tg-emoji emoji-id="5257965174979042426">📝</tg-emoji> 编辑代码',
    "img": '<tg-emoji emoji-id="4958587679361991667">🔍</tg-emoji> 图片识别',
    "coin": '<tg-emoji emoji-id="4983742125993625574">💰</tg-emoji> 查询币价',
    "tg": '<tg-emoji emoji-id="4958587679361991667">🔍</tg-emoji> TG双号',
    "file": '<tg-emoji emoji-id="5257965810634202885">📁</tg-emoji> 生成文件',
    "pdf": '<tg-emoji emoji-id="5258477770735885832">📄</tg-emoji> 生成PDF',
    "notify": '<tg-emoji emoji-id="5118842246434653222">📢</tg-emoji> 发送通知',
    "captcha": '<tg-emoji emoji-id="4927020030513644819">🔐</tg-emoji> 打码识别',
    "sys": '<tg-emoji emoji-id="4927394697690744536">⚙️</tg-emoji> 系统操作',
    "group": '<tg-emoji emoji-id="5118364710495847757">👥</tg-emoji> 群组管理',
    "data": '<tg-emoji emoji-id="5190806721286657692">📊</tg-emoji> 数据查询',
    "project": '<tg-emoji emoji-id="5422351255777321154">📋</tg-emoji> 项目管理',
    "waf": '<tg-emoji emoji-id="4983248299243866319">🛡️</tg-emoji> WAF逃逸',
    "playbook": '<tg-emoji emoji-id="5256131095094652290">🎯</tg-emoji> 自动化渗透',
    "report": '<tg-emoji emoji-id="5257965174979042426">📝</tg-emoji> 生成报告',
    "schedule": '<tg-emoji emoji-id="4983515360310336168">⏰</tg-emoji> 定时任务',
    "parse": '<tg-emoji emoji-id="5215324073944423501">📥</tg-emoji> 解析输出',
    "memory": '🧠 记忆检索',
    "conversation_search": '<tg-emoji emoji-id="4958587679361991667">🔍</tg-emoji> 对话搜索',
    "group_memory": "👥 群聊记忆",
}

TOOLS = [
 {"type":"function","function":{"name":"sh","description":"Run shell command","parameters":{"type":"object","properties":{"cmd":{"type":"string"}},"required":["cmd"]}}},
 {"type":"function","function":{"name":"read","description":"Read file","parameters":{"type":"object","properties":{"path":{"type":"string"}},"required":["path"]}}},
 {"type":"function","function":{"name":"write","description":"Write file","parameters":{"type":"object","properties":{"path":{"type":"string"},"text":{"type":"string"}},"required":["path","text"]}}},
 {"type":"function","function":{"name":"edit","description":"Replace text in file","parameters":{"type":"object","properties":{"path":{"type":"string"},"old":{"type":"string"},"new":{"type":"string"}},"required":["path","old","new"]}}},
 {"type":"function","function":{"name":"search","description":"联网搜索(Bing+DDG+Marginalia+DDG库 四引擎并行, 结果按命中引擎数排序)。act=search 普通搜索(快, 2-5秒, 要最新资料/新闻/事实就用它); act=deep 深度检索(自动5路子查询+并行抓4-6篇正文全文, 5-10秒, 适合需要全面了解/对比/调研的问题)。多个不相关问题可就同一轮并行发多个 search。","parameters":{"type":"object","properties":{"q":{"type":"string","description":"搜索词或问题(中文英文都行; 支持 site: filetype: 等语法)"},"act":{"type":"string","description":"search=普通搜索(默认) | deep=深度检索(多路子查询+抓正文)"},"limit":{"type":"integer","description":"返回条数, 默认8"}},"required":["q"]}}},
 {"type":"function","function":{"name":"sys","description":"System:info/docker/svc/git/install","parameters":{"type":"object","properties":{"act":{"type":"string"},"tgt":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"url","description":"网页/资源工具。act=dl【首选·下载视频音乐】yt-dlp(抖音/B站/油管/TikTok/音乐平台全支持, 纯音频加 audio=true 自动转mp3), 下完自动发给用户; act=download 普通直链(curl: 图片/zip/apk/文本); act=fetch 抓页面; act=extract 抽链接/邮箱/手机号/JS; act=post 带data发POST。下载需求一律用本工具, 不要用sh+curl手写。","parameters":{"type":"object","properties":{"url":{"type":"string"},"act":{"type":"string","description":"dl=流媒体下载(首选) | download=直链下载 | fetch=抓页面 | extract=抽信息 | post=POST"},"audio":{"type":"boolean","description":"act=dl 时 true=只提取音频转mp3(下音乐/歌曲必传)"},"name":{"type":"string","description":"act=dl/download 时的文件名(下音乐建议传「歌名-歌手」, 用户看到的文件名和播放器标题就是它; 不传则自动清洗平台标题)"},"cookie":{"type":"string"},"data":{"type":"string"},"name":{"type":"string"}},"required":["url"]}}},
 {"type":"function","function":{"name":"file","description":"文件收发: 小文本用name+text(≤3000字); 大文件/已有文件必须用 act=send + path=磁盘路径(机器直发,任意大小不截断,如/opt/deepseek-bot/xx.csv或/tmp/tg_file_xxx.txt)","parameters":{"type":"object","properties":{"name":{"type":"string"},"text":{"type":"string"},"act":{"type":"string","description":"send=发送已有磁盘文件(大文件必用)"},"path":{"type":"string","description":"要发送的磁盘文件绝对路径(act=send时填)"}},"required":["name"]}}},
 {"type":"function","function":{"name":"coin","description":"Crypto price","parameters":{"type":"object","properties":{"coin":{"type":"string"}},"required":["coin"]}}},

 {"type":"function","function":{"name":"proxy","description":"IP代理池(仅管理员): status查看(会实测并显示策略)/set tunnel设置/rotate换IP/off关闭。**默认是直连优先**——代理按流量计费,服务器本身出网正常时用不到它; 只有目标直连不通、或明确要求隐藏服务器真实IP时才 act=on 临时开全程代理, 用完 act=auto 关回直连优先。url/sh/fetch 已经会自动兜底(直连不通才换代理), 多数情况不用管","parameters":{"type":"object","properties":{"act":{"type":"string"},"value":{"type":"string"},"url":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"fofa","description":"FOFA空间测绘(仅管理员), 用来从全网找资产/后台/站点。用户说 fofo/fofa/测绘/找后台/找资产/扫全网 都是指这个工具。q=FOFA语法, 三种情况都要会: ①给了域名→ q='host=\"x.com\"'; ②给了IP→ q='ip=\"1.2.3.4\"'; ③**只给了业务关键词(飞投/下注/棋牌/后台/菠菜/支付这类)也要直接搜, 不要反过来要域名** → 把词拼进语法, 例 q='title=\"后台\" && body=\"下注\"', 可选再叠 country=\"CN\" && port=\"443\"。limit=条数(默认20)。英文/拼音关键词命中率更高(如 body=\"bet\" 而非 body=\"下注\")。","parameters":{"type":"object","properties":{"act":{"type":"string"},"q":{"type":"string"},"limit":{"type":"integer"}},"required":["q"]}}},
 {"type":"function","function":{"name":"selfext","description":"自我扩展: 现有工具覆盖不了时自己造一个插件(免改主程序, 写完自动自测+热加载, 立即可用)。op=propose新建/list列出/test试跑/remove删除/code看源码。propose 需要: name(小写字母数字下划线)/description(模型何时该用它)/schema(JSON Schema 字符串)/script(python源码, 从 sys.argv[1] 读 JSON 参数, print 结果)/test_args(自测参数JSON)。自测失败会自动回滚并返回报错, 你改完再 propose 一次。","parameters":{"type":"object","properties":{"op":{"type":"string","enum":["propose","list","test","remove","code"]},"name":{"type":"string"},"description":{"type":"string"},"schema":{"type":"string"},"script":{"type":"string"},"test_args":{"type":"string"},"args":{"type":"string"},"timeout":{"type":"integer"}},"required":["op"]}}},
 {"type":"function","function":{"name":"watch","description":"值守任务(自主盯梢): 定期检查目标, **只在变化时**通知你, 可选变化后自动深挖。op=add/list/del/pause/resume/run/status。kind=http(抓页面/接口, 可配 grep 正则)/cmd(跑命令看输出)/port(TCP端口状态)/file(文件哈希)/keyword(搜关键词看新增结果); interval=秒; then=deep(变化后自动深度分析)。","parameters":{"type":"object","properties":{"op":{"type":"string","enum":["add","list","del","pause","resume","run","status"]},"name":{"type":"string"},"kind":{"type":"string"},"target":{"type":"string"},"grep":{"type":"string"},"interval":{"type":"integer"},"notify":{"type":"string"},"then":{"type":"string"},"wid":{"type":"string"},"chat":{"type":"integer"}},"required":["op"]}}},
 {"type":"function","function":{"name":"todo","description":"任务清单(多步任务先列计划再逐项执行, 用户能看见进度): op=set列出/替换全部步骤(用 | 分隔, 如 存活探测|端口扫描|目录爆破|漏洞验证) / done标记某步完成(n=序号或关键词) / doing标记进行中 / add追加 / list查看 / clear清空。**渗透/多步任务动手前必须先 todo set 列计划**, 每完成一步就 todo done, 用户全程看得到打勾进度。","parameters":{"type":"object","properties":{"op":{"type":"string","enum":["set","add","done","doing","list","clear"]},"steps":{"type":"string"},"n":{"type":"integer"},"text":{"type":"string"}},"required":["op"]}}},
 {"type":"function","function":{"name":"team","description":"多AI协作(仅管理员): act=plan拆解/run并行执行/auto拆+并行+汇总一条龙 task=目标。编排层: 六角色分派(侦察兵recon/代码审计师audit/利用工程师exploit/免杀绕过evasion/内网渗透lateral/取证报告员report)+流程锁定(P0信息收集→P1打点→P2权限维持→P3内网横移→P4数据定位→P5痕迹清理与报告)+漏洞覆盖矩阵; 复杂任务/多攻击面目标建议用team","parameters":{"type":"object","properties":{"act":{"type":"string"},"task":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"subagent","description":"派子代理(独立上下文): 它有自己的工具循环, 只把最终结果回给你, **不占你的上下文**。适合: ①要翻很多文件/抓很多网页才能得出结论的调研 ②彼此独立的子任务可并行 ③大范围检索(避免把主对话撑爆)。task=任务描述, **必须自成一体的完整描述(子代理看不到我们的对话)**; act=run(单个)/parallel(并行多个, 用 tasks 传数组≤5); role 可选 recon/audit/exploit/evasion/lateral/report; rounds 默认200(长活直接给到600, token 管够别省) —— 默认轮次已够长, 不用你手填。**同一批子代理共用一块黑板, 能用 `SAY: 一句话` 互相交流**。上限: 管理员 rounds≤600/并行≤32, 普通用户 rounds≤3/并行≤2(超了会自动按上限执行, 别对外报超过上限的数字)","parameters":{"type":"object","properties":{"task":{"type":"string","description":"自成一体的完整任务描述"},"tasks":{"type":"array","items":{"type":"string"},"description":"act=parallel 时的多个任务(≤5)"},"act":{"type":"string","enum":["run","parallel"]},"role":{"type":"string"},"rounds":{"type":"integer"}},"required":[]}}},
 {"type":"function","function":{"name":"workflow","description":"通用并行编排(fan-out): 把一个目标拆成**一批彼此独立的子任务**, 每个子任务派一个独立上下文的子代理并行干, 结果分段回给你(不占你的上下文)。比 team 通用: team 是固定六角色, workflow 是任意任务清单。tasks=子任务数组(≤8, 也可用|分隔); stages=阶段数(默认1, ≤4): 第N阶段的输入是上一阶段**该任务自己的**结果(纵向流水线, 不跨任务串味); stage_next=第2阶段起的任务模板, 用 {prev} 引用上一步结果; concurrency=并发(默认2, ≤4); role/rounds 可选。rounds 默认200(上限600)。**同一批任务的子代理共用黑板, 可用 `SAY: 一句话` 互相交流**。上限: 管理员 tasks≤32/stages≤8/并发≤32/rounds≤600, 普通用户 tasks≤3/stages≤2/并发≤2/rounds≤3(超了自动按上限执行)。适合: 多个目标批量扫/多个文件分别审/先收集再逐个深挖","parameters":{"type":"object","properties":{"tasks":{"type":"array","items":{"type":"string"}},"stages":{"type":"integer"},"stage_next":{"type":"string"},"concurrency":{"type":"integer"},"role":{"type":"string"},"rounds":{"type":"integer"}},"required":["tasks"]}}},
 {"type":"function","function":{"name":"ralph","description":"全新上下文迭代(ralph): 每轮都开一个**没有任何对话历史的**子代理, 只把'目标+前面各轮的结论链'交给它 —— 上下文永远干净, 不会越跑越钻牛角尖; 进展靠状态文件累积。适合: 反复试错型的长任务(调参/爆破式排查/逐步逼近)、上下文已经被污染需要'重开一局'的活。objective=目标(每轮原样交给新代理, 不可变); rounds=最多几轮(默认40, 管理员≤150/普通用户≤3)。子代理会被要求用 RALPH_STATE: COMPLETE|BLOCKED|CONTINUE + RALPH_NOTE: 一句话 结尾; 遇到 COMPLETE/BLOCKED 会提前收敛。注意: 每轮都看不到上一轮的过程, 所以**结论必须写进 RALPH_NOTE**","parameters":{"type":"object","properties":{"objective":{"type":"string"},"rounds":{"type":"integer"},"role":{"type":"string"}},"required":["objective"]}}},
 {"type":"function","function":{"name":"goal","description":"持久目标: 把一件要跨多轮才能完成的活钉在会话上, 没做完会自动一轮轮接着干(不用用户催)。act=set(task=目标, max=最多几轮默认40; 管理员≤300/普通用户≤5)/status/done/block(note=卡在哪)/pause/resume/drop/note(note=本轮备注)。规则: 每轮收尾若目标仍active→自动续跑(轮次+1); 到max自动停并通知用户; 用户说「停/算了」自动暂停; 达成后**必须**调用 act=done(否则会被继续续跑)。一次就能答完的活别用","parameters":{"type":"object","properties":{"act":{"type":"string","enum":["set","status","done","block","pause","resume","drop","note"]},"task":{"type":"string"},"max":{"type":"integer"},"note":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"lateral","description":"横向移动","parameters":{"type":"object","properties":{"act":{"type":"string"},"target":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"privesc","description":"提权","parameters":{"type":"object","properties":{"act":{"type":"string"},"target":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"credential","description":"凭证攻击: act=spray/responder_start/responder_stop target=目标 interface=网卡 timeout=秒","parameters":{"type":"object","properties":{"act":{"type":"string"},"target":{"type":"string"},"interface":{"type":"string"},"timeout":{"type":"integer"}},"required":["act"]}}},
 {"type":"function","function":{"name":"adaptive_chain","description":"自适应攻击链","parameters":{"type":"object","properties":{"act":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"api_attack","description":"API攻击: act=rest/graphql","parameters":{"type":"object","properties":{"act":{"type":"string"},"url":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"c2","description":"C2集成: act=start/status protocol=sliver host port","parameters":{"type":"object","properties":{"act":{"type":"string"},"protocol":{"type":"string"},"host":{"type":"string"},"port":{"type":"integer"}},"required":["act"]}}},
 {"type":"function","function":{"name":"strix","description":"Strix AI渗透测试(34k stars): act=run/recon/full/quick target=目标","parameters":{"type":"object","properties":{"act":{"type":"string"},"target":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"cloud","description":"云攻击","parameters":{"type":"object","properties":{"act":{"type":"string"},"target":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"container","description":"容器逃逸","parameters":{"type":"object","properties":{"act":{"type":"string"},"target":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"evasion","description":"规避引擎","parameters":{"type":"object","properties":{"act":{"type":"string"},"target":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"exfil","description":"数据外传: act=discover/quick/pack/encrypt/split/send/script","parameters":{"type":"object","properties":{"act":{"type":"string"},"target":{"type":"string"}},"required":["act"]}}},
 
 {"type":"function","function":{"name":"img","description":"Image OCR","parameters":{"type":"object","properties":{"act":{"type":"string"},"path":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"shot","description":"Screenshot URL","parameters":{"type":"object","properties":{"url":{"type":"string"}},"required":["url"]}}},
 {"type":"function","function":{"name":"pdf","description":"Create/read PDF","parameters":{"type":"object","properties":{"act":{"type":"string"},"path":{"type":"string"},"text":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"group","description":"Group群组管理:extract提取成员/kick踢人/cleanup全群批量清(仅管理员, dry_run=True全群扫描统计无头像与无用户名与广告特征人数不踢, dry_run=False执行踢, mode=both默认无头像或无用户名/no_photo只踢无头像/no_username只踢无用户名(含NFT判定)/ad只踢广告特征(名字含礼物代开回收会员telegram星星等)/all全部合并, limit=最多踢N个)/pin置顶/unpin取消置顶/rename改名/desc改简介/poll投票/delmsg删消息/myperm查权限/members2成员数/members/find按名字反查成员uid(name=昵称或用户名片段,返回uid|名字|@用户名)/photo设群头像(path=图片路径)/delphoto删头像/perm群权限/mute禁言(uid+seconds)/unmute解禁/promote提升管理员(uid+custom头衔)/demote取消管理/invite邀请链接(expire秒+limit次数)/revokeinvite撤销邀请/info群详情(含community字段)/member成员详情(uid)(仅管理员,info/member/members2/photo/delphoto/perm/mute/unmute/promote/demote/invite/revokeinvite部分需bot有管理员权限)。gid可省略=自动用当前群(用户在哪个群调用就操作哪个群);换群操作才传gid; 要【删/禁言某人】先用 find 拿uid再操作","parameters":{"type":"object","properties":{"act":{"type":"string"},"uid":{"type":"integer"},"gid":{"type":"integer"},"mid":{"type":"integer"},"title":{"type":"string"},"text":{"type":"string"},"question":{"type":"string"},"options":{"type":"string"},"is_anon":{"type":"boolean"},"dry_run":{"type":"boolean"},"mode":{"type":"string"},"limit":{"type":"integer"}},"required":["act"]}}},
 {"type":"function","function":{"name":"data","description":"Bot data:users/profiles/memory","parameters":{"type":"object","properties":{"act":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"ask","description":"向用户提问并等待回答(需要用户决策/确认时用): q=问题, opts=选项(用|或,分隔, 最多8个), multi=true多选/false单选。用户点按钮或直接打字回复均可; 无自动超时, 一直等用户回答。返回值=用户的选择","parameters":{"type":"object","properties":{"q":{"type":"string"},"opts":{"type":"string"},"multi":{"type":"boolean"}},"required":["q","opts"]}}},
 {"type":"function","function":{"name":"memory","description":"长期记忆:add添加事实/search语义搜索/stats统计/pref设置偏好/summarize手动摘要。自动跨会话持久化。","parameters":{"type":"object","properties":{"act":{"type":"string","enum":["add","search","stats","pref","summarize","clear"]},"key":{"type":"string"},"value":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"group_memory","description":"群聊记忆:stats查看群聊统计(当前群)/profile查看某人群友画像(uid参数).群消息自动收录.","parameters":{"type":"object","properties":{"act":{"type":"string","enum":["stats","profile"]},"uid":{"type":"integer"}},"required":["act"]}}},
 {"type":"function","function":{"name":"conversation_search","description":"搜索历史对话:search用户对话/search_all全局搜索/topics最近话题","parameters":{"type":"object","properties":{"act":{"type":"string","enum":["search","search_all","topics"]},"query":{"type":"string"},"uid":{"type":"integer"},"limit":{"type":"integer"}},"required":["act","query"]}}},
 {"type":"function","function":{"name":"whois","description":"查TG用户名→用户ID(主账号秒查,别用tg双号绕路): name=用户名(带不带@都行,如 leileyiqie)","parameters":{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}}},
 {"type":"function","function":{"name":"tg","description":"TG双号控制:acct1/acct2两个号,dialogs会话列表/messages读消息/send发消息/search搜索/stats统计/whois排行/members成员/join加群/dual双号连发/user查用户/group_info查群/react点赞+回复(格式:wang:群名:消息ID:emoji 或 bot:群ID:消息ID:内容,内容可以是emoji点赞或文字回复,自动判断用@YOUR_ALT_BOT)","parameters":{"type":"object","properties":{"act":{"type":"string"},"tgt":{"type":"string"}},"required":["act","tgt"]}}},
 {"type":"function","function":{"name":"notify","description":"发 TG 消息/通知(Bot API 10.3)。to=目标 chat_id(群为负); text=正文(markdown 可, 自动转 HTML 并补自定义动画表情)。★长文或含 <details>/<table>/<h1>/<hr> 等块标签时会自动走富文本通道(上限 32768 字), 否则走普通消息(4096) —— 发报表/汇总/报告直接写长文即可, 不用自己截断。buttons=inline 按钮, 每内层数组是一行; 元素 ['文字','callback_data'] 或 {'text':'...','url':'...','style':'success','icon':'💳'}(style=primary/success/danger 给按钮上色; icon 传表情本身如 💳, 会自动映射成官方 icon_custom_emoji_id)。可选: reply_to=引用的 message_id; ephemeral=只对该用户可见且自动消失的临时消息(直接传用户 uid); silent=true 静默发送不响铃; critical=true 紧急通知(不受每分钟条数配额限制); topic=话题号; want_mid=true 时返回 message_id(便于之后编辑或删除这条通知)。收款按钮: 先用 paylink 拿 url, 再 buttons=[{'text':'支付 xx USDT','url':链接,'style':'success','icon':'💳'}]","parameters":{"type":"object","properties":{"to":{"type":"integer","description":"目标 chat_id(群为负数)"},"text":{"type":"string","description":"正文, 支持 markdown(加粗/标题/表格/代码块/引用)"},"buttons":{"type":"array","description":"inline 按钮, 每内层数组=一行; 元素 ['文字','callback_data'] 或 {'text','url','style','icon'}","items":{"type":"array","items":{"type":"object"}}},"reply_to":{"type":"integer","description":"引用的 message_id"},"ephemeral":{"description":"临时消息(只对该用户可见并自动消失): 直接传用户 uid"},"silent":{"type":"boolean","description":"静默发送(不响铃)"},"critical":{"type":"boolean","description":"紧急通知, 不受每分钟条数配额限制"},"topic":{"type":"integer","description":"话题号(message_thread_id)"},"want_mid":{"type":"boolean","description":"true 时返回 message_id"}},"required":["to","text"]}}},
 {"type":"function","function":{"name":"agent_reach","description":"AI全网情报(Agent-Reach 0.1.0):读RSS源/YouTube字幕/查渠道状态. 用法: agent_reach cmd, 如 'list'列渠道 / 'get rss.feed https://xxx/feed/ --limit 3' 读RSS / 'get youtube.transcript https://youtu.be/XXX --max-tokens 4000' 读字幕 / 'doctor' 检查渠道状态","parameters":{"type":"object","properties":{"cmd":{"type":"string"}},"required":["cmd"]}}},
 {"type":"function","function":{"name":"captcha","description":"CapMonster打码:text/recaptcha/hcaptcha/funcaptcha/turnstile/slide/balance","parameters":{"type":"object","properties":{"act":{"type":"string","enum":["text","recaptcha","recaptcha_v3","hcaptcha","funcaptcha","turnstile","slide","balance"]},"path":{"type":"string"},"url":{"type":"string"},"sitekey":{"type":"string"},"invisible":{"type":"boolean"},"min_score":{"type":"number"},"subdomain":{"type":"string"}},"required":["act"]}}},
 {"type":"function","function":{"name":"project","description":"项目管理:create/list/switch/delete/stats","parameters":{"type":"object","properties":{"act":{"type":"string","enum":["create","list","switch","delete","stats","active"]},"name":{"type":"string"},"target":{"type":"string"},"id":{"type":"integer"}},"required":["act"]}}},
 {"type":"function","function":{"name":"playbook","description":"自动化渗透:recon(信息收集)/ports(端口)/web(Web扫描)/vuln(漏洞)/full(全流程)/batch(多目标并行).需先创建项目.batch模式支持project_ids列表并发扫描.","parameters":{"type":"object","properties":{"act":{"type":"string","enum":["recon","ports","web","vuln","full","batch"]},"target":{"type":"string"},"project_id":{"type":"integer"},"phases":{"type":"string"},"project_ids":{"type":"string"},"max_workers":{"type":"integer"}},"required":["act"]}}},
 {"type":"function","function":{"name":"waf","description":"WAF逃逸引擎:生成绕过变体(encode)/测试绕过(test)/一键逃逸(evade).支持sqli/xss/cmdi/lfi/ssti/ssrf六种攻击类型+12种编码策略+HTTP方法头绕过.","parameters":{"type":"object","properties":{"act":{"type":"string","enum":["encode","test","evade","profile"]},"attack_type":{"type":"string","enum":["sqli","xss","cmdi","lfi","ssti","ssrf"]},"payload":{"type":"string"},"target":{"type":"string"},"url_param":{"type":"string"},"waf_type":{"type":"string"},"project_id":{"type":"integer"}},"required":["act","attack_type","payload"]}}},
 {"type":"function","function":{"name":"report","description":"生成渗透报告:summary/md/pdf/export","parameters":{"type":"object","properties":{"act":{"type":"string","enum":["summary","md","pdf","export"]},"project_id":{"type":"integer"},"format":{"type":"string"}},"required":["act","project_id"]}}},
 {"type":"function","function":{"name":"schedule","description":"定时任务:add/list/toggle/delete","parameters":{"type":"object","properties":{"act":{"type":"string","enum":["add","list","toggle","delete"]},"project_id":{"type":"integer"},"name":{"type":"string"},"cron":{"type":"string"},"action":{"type":"string"},"target":{"type":"string"},"id":{"type":"integer"}},"required":["act"]}}},
 {"type":"function","function":{"name":"parse","description":"解析工具输出:自动识别nmap/nuclei/sqlmap/ffuf/subfinder/httpx/whatweb/wapiti/nikto/xsstrike/commix/wpscan/dnsx/testssl/shodan/gobuster/feroxbuster/dirsearch/arjun/wafw00f/amass/auto-verify(20+工具)","parameters":{"type":"object","properties":{"tool":{"type":"string"},"text":{"type":"string"},"project_id":{"type":"integer"}},"required":["tool","text"]}}},
]

HEAVY_KW = {"lateral":("横向","横向移动"), "privesc":("提权","后门提权"), "credential":("凭证","密码喷洒","responder","喷密码"), "adaptive_chain":("自适应攻击","adaptive"), "api_attack":("api攻击","graphql","rest api攻击"), "c2":("c2","sliver","c2集成"), "strix":("strix",), "cloud":("云攻击","aws","azure","s3桶","云环境"), "container":("容器","docker","k8s","kubernetes","容器逃逸"), "evasion":("规避","免杀","evasion"), "exfil":("外传","外泄","打包数据","数据窃取","payload外发"), "fofa":("fofa","fofo","foa","资产测绘","找后台","找资产","扫全网")}


# ★2026-10-05 补齐工具标签: 原来只有 26 条 / 50 个工具 → 一半工具在面板与心跳里显示成裸名 "🔧 name"。
#   用 update 追加, 不改原字面量(TOOL_LABELS 这个对象 bot.py 已 import, 原地改动对它可见)。
TOOL_LABELS.update({
    "todo": "📋 任务清单", "watch": "👁 值守监控", "goal": "🎯 持久目标",
    "subagent": "🤖 子代理", "workflow": "🔀 工作流", "ralph": "🔁 迭代循环",
    "selfext": "🧩 自我扩展", "ask": "❓ 提问按钮", "whois": "🌐 域名查询",
    "proxy": "🛡 代理池", "fofa": "🛰 资产测绘",
    "team": "👥 多AI协作", "strix": "🕷 Strix渗透", "agent_reach": "📡 全网情报",
    "lateral": "↔️ 横向移动", "privesc": "⬆️ 提权", "credential": "🔑 凭证攻击",
    "adaptive_chain": "⛓ 自适应攻击链", "api_attack": "🔌 API攻击",
    "c2": "🛰 C2集成", "cloud": "☁️ 云攻击", "container": "📦 容器逃逸",
    "evasion": "🥷 规避引擎", "exfil": "📤 数据外传",
})
